In [29]:
import pandas as pd

In [31]:
df = pd.read_csv('blinkit_data.csv')

In [33]:
df.head()

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0
2,Regular,FDR28,Frozen Foods,2010,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0
3,Regular,FDL50,Canned,2000,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0

In [11]:
df.columns

Index(['Item Fat Content', 'Item Identifier', 'Item Type',
       'Outlet Establishment Year', 'Outlet Identifier',
       'Outlet Location Type', 'Outlet Size', 'Outlet Type', 'Item Visibility',
       'Item Weight', 'Sales', 'Rating'],
      dtype='object')

In [15]:
df['Item Type'].value_counts()

Item Type
Fruits and Vegetables    1232
Snack Foods              1200
Household                 910
Frozen Foods              856
Dairy                     682
Canned                    649
Baking Goods              648
Health and Hygiene        520
Soft Drinks               445
Meat                      425
Breads                    251
Hard Drinks               214
Others                    169
Starchy Foods             148
Breakfast                 110
Seafood                    64
Name: count, dtype: int64

In [19]:
df[df['Item Weight']>12.0]

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0
2,Regular,FDR28,Frozen Foods,2010,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0
3,Regular,FDL50,Canned,2000,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0
7,Low Fat,NCD30,Household,2015,OUT045,Tier 2,Small,Supermarket Type1,0.026904,19.70,96.0726,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8240,reg,FDN50,Canned,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.026628,16.85,93.7120,4.0
8241,reg,FDH26,Canned,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.034841,19.25,141.1496,4.0
8242,reg,FDG56,Fruits and Vegetables,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.071744,13.30,59.7536,4.0
8244,reg,FDX57,Snack Foods,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.047459,17.25,95.8068,4.0
8245,reg,FDD10,Snack Foods,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.046208,20.60,178.0344,4.0

In [23]:
df.shape

(8523, 12)

In [25]:
df.info

<bound method DataFrame.info of      Item Fat Content Item Identifier              Item Type  \
0             Regular           FDX32  Fruits and Vegetables
1             Low Fat           NCB42     Health and Hygiene
2             Regular           FDR28           Frozen Foods
3             Regular           FDL50                 Canned
4             Low Fat           DRI25            Soft Drinks
...               ...             ...                    ...
8518          low fat           NCT53     Health and Hygiene
8519          low fat           FDN09            Snack Foods
8520          low fat           DRE13            Soft Drinks
8521              reg           FDT50                  Dairy
8522              reg           FDM58            Snack Foods

      Outlet Establishment Year Outlet Identifier Outlet Location Type  \
0                          2012            OUT049               Tier 1
1                          2022            OUT018               Tier 3
2                          2010            OUT046               Tier 1
3                          2000            OUT013               Tier 3
4                          2015            OUT045               Tier 2
...                         ...               ...                  ...
8518                       1998            OUT027               Tier 3
8519                       1998            OUT027               Tier 3
8520                       1998            OUT027               Tier 3
8521                       1998            OUT027               Tier 3
8522                       1998            OUT027               Tier 3

     Outlet Size        Outlet Type  Item Visibility  Item Weight     Sales  \
0         Medium  Supermarket Type1         0.100014        15.10  145.4786
1         Medium  Supermarket Type2         0.008596        11.80  115.3492
2          Small  Supermarket Type1         0.025896        13.85  165.0210
3           High  Supermarket Type1         0.042278        12.15  126.5046
4          Small  Supermarket Type1         0.033970        19.60   55.1614
...          ...                ...              ...          ...       ...
8518      Medium  Supermarket Type3         0.000000          NaN  164.5526
8519      Medium  Supermarket Type3         0.034706          NaN  241.6828
8520      Medium  Supermarket Type3         0.027571          NaN   86.6198
8521      Medium  Supermarket Type3         0.107715          NaN   97.8752
8522      Medium  Supermarket Type3         0.000000          NaN  112.2544

      Rating
0        5.0
1        5.0
2        5.0
3        5.0
4        5.0
...      ...
8518     4.0
8519     4.0
8520     4.0
8521     4.0
8522     4.0

[8523 rows x 12 columns]>

In [27]:
df.dtypes

Item Fat Content              object
Item Identifier               object
Item Type                     object
Outlet Establishment Year      int64
Outlet Identifier             object
Outlet Location Type          object
Outlet Size                   object
Outlet Type                   object
Item Visibility              float64
Item Weight                  float64
Sales                        float64
Rating                       float64
dtype: object